version: 0.2

phases:
 install:
   commands:
     - npm install
     - npm install -g mocha
     - npm install -g serverless

 build:
   commands:
     - echo “--------- Starting Dev Serverless Deploy ---------”
     - devtemp_role=$(aws sts assume-role --role-arn “arn:aws:iam::${ACCOUNT_NUMBER}:role/X-Account-Serverless-Deploy” --role-session-name DevAWSCLI-Session)
     - export AWS_ACCESS_KEY_ID=$(echo $devtemp_role | jq .Credentials.AccessKeyId | xargs)
     - export AWS_SECRET_ACCESS_KEY=$(echo $devtemp_role | jq .Credentials.SecretAccessKey | xargs)
     - export AWS_SESSION_TOKEN=$(echo $devtemp_role | jq .Credentials.SessionToken | xargs)
     - serverless deploy --verbose --stage dev --region us-west-2 || exit 1
     - unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
 post_build:
   commands:
     - npm test
       

