service:
  name: ItemService
  BASE_PATH: items

provider:
  name: aws
  runtime: nodejs6.10
  endpointType: regional
  region: ${env:REGION, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  tracing: true
  basePath: 'item'
  environment:
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
    NODE_ENV: ${opt:stage, 'dev'}
    TABLE: 'Items'  #This is the DyanmoDB Table name  ***** PLEASE SET
  deploymentBucket:
    name: ${self:provider.stage}-${self:provider.region}-nuskin-sls
    # serverSideEncryption: AES256 # when using server-side encryption
package: # Optional deployment packaging configuration
  exclude:
    - README.md
    - buildspec.yml
    - test/**


  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE}"
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"


functions:
  ItemService: #This is the name of your Lambda Function  ***** PLEASE SET
    handler: src/index.handler
    events:
     - http:
        path: /{id}
        method: get
        cors: true
        request:
          parameters:
            paths:
              id: true
     - http:
        path: /
        method: post
        cors: true
     - http:
        path: /{id}
        method: delete
        cors: true
        request:
          parameters:
            paths:
              userId: true




#CI/CD Deployment configuration update with caution

custom:
  stage: ${opt:stage, self:provider.stage}
  api-domains:
    prod: api.cloud.nuskin.com
    stage: stageapi.cloud.nuskin.com
    test: testapi.cloud.nuskin.com
    dev: devapi.cloud.nuskin.com

  customDomain:
      basePath: ${self:provider.basePath}
      domainName: ${self:custom.api-domains.${self:custom.stage}}
      stage: ${self:custom.stage}
      certificateName: '*.cloud.nuskin.com'
      endpointType: 'regional'
      createRoute53Record: false

  logARN:
    prod: arn:aws:lambda:us-west-2:878096462359:function:LogsToES-prod-LogsToES
    stage: arn:aws:lambda:us-west-2:453549906622:function:LogsToES-stage-LogsToES
    test: arn:aws:lambda:us-west-2:105371274045:function:LogsToES-test-LogsToES
    dev: arn:aws:lambda:us-west-2:140547422257:function:LogsToES-dev-LogsToES

  logForwarding:
    destinationARN: ${self:custom.logARN.${self:custom.stage}}
    filterPattern: '[timestamp=*Z, request_id="*-*", event]'



plugins:
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-domain-manager
  - serverless-log-forwarding
