service: Item

provider:
  name: aws
  runtime: nodejs6.10
  endpointType: regional
  region: ${env:REGION, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  envir:  ${env:DEP_ENVIRONMENT, 'dev'}
  tracing: true
  environment:
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR

 # deploymentBucket:
 #   name: ${self:provider.envir}-${self:provider.region}-nuskin-sls
    # serverSideEncryption: AES256 # when using server-side encryption
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"


functions:
  Item:
    environment:
      TABLE: 'Items'
    handler: src/index.handler
    events:
     - http:
        path: /{id}
        method: get
        cors: true
        request:
          parameters:
            paths:
              id: true
     - http:
        path: /
        method: post
        cors: true
     - http:
        path: /{id}
        method: delete
        cors: true
        request:
          parameters:
            paths:
              userId: true

custom:
  customDomain:
    domainName: 'api.nuskin.io' # Change this to your domain.
    basePath: 'Item' # This will be prefixed to all routes
    stage: ${self:provider.stage}

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.cloud.nuskin.com
    stage: stageapi.cloud.nuskin.com
    test: testapi.cloud.nuskin.com
    dev: devapi.cloud.nuskin.com

  customDomain:
    basePath: 'favorites'
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: '${self:custom.stage}'
    certificateName: '*.cloud.nuskin.com'
    endpointType: 'regional'
    createRoute53Record: false
 #  domainName: 'api.nuskin.io' # Change this to your domain.
 #  basePath: 'Item' # This will be prefixed to all routes
 #  stage: ${self:provider.stage}


plugins:
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-domain-manager
  - serverless-aws-alias





