service: ItemService

provider:
  name: aws
  runtime: nodejs6.10
  endpointType: regional
  region: 'us-west-2'
  stage: ${opt:stage, 'dev'}
  tracing: true
  basePath: 'item' #This is the path  ***** PLEASE SET
  environment:
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
    NODE_ENV: ${opt:stage, 'dev'}
    TABLE: 'Items'  #This is the DyanmoDB Table name  ***** PLEASE SET
  deploymentBucket:
    name: ${self:provider.stage}-${self:provider.region}-nuskin-sls

  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE}*"
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

resources:
  Resources:
    ####################################################
    ###Remove section if not creating DynamoDB tables###
    ####################################################
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE}
        AttributeDefinitions:
          - AttributeName: country
            AttributeType: S
        KeySchema:
          - AttributeName: country
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
    ####################################################

functions:
  MicroService: ${self:provider.basePath} #This is the name of your Lambda Function  ***** PLEASE SET
    handler: src/index.handler
    events:
     - http:
        path: /{id}
        method: get
        cors:
          origin: '*'
          headers:
            - '*'
          allowCredentials: false
        request:
          parameters:
            paths:
              id: true
     - http:
        path: /
        method: post
        cors:
          origin: '*'
          headers:
            - '*'
          allowCredentials: false
     - http:
        path: /{id}
        method: delete
        cors:
          origin: '*'
          headers:
            - '*'
          allowCredentials: false
        request:
          parameters:
            paths:
              userId: true


#CI/CD Deployment configuration update with caution
custom:
  ###Used for Assigning Function to Custom API Domain
  customDomain:
      basePath: ${self:provider.basePath}
      domainName: ${ssm:/global/apidomain,'devapi.cloud.nuskin.com' }
      stage: ${self:provider.stage}
      certificateName: '*.cloud.nuskin.com'
      endpointType: 'regional'
      createRoute53Record: false

  ###Used for Automatically subscribing cloudwatch Lambda logs to ElasticSearch Service Lambda
  logForwarding:
    destinationARN: ${ssm:/global/logarn, 'arn:aws:lambda:us-west-2:140547422257:function:LogsToES-dev-LogsToES'}
    filterPattern: '[timestamp=*Z, request_id="*-*", event]'

  #############################################################
  ###Used for Setting up DynamoDB Autoscaling               ###
  ###Remove section if not creating DynamoDB tables         ###
  #############################################################
  capacities:
    - table: DynamoDBTable  # DynamoDB Resource Name - Not the Table Name
      # index:              # List or single index name
      #   - custom-index-name
      read:
        minimum: 5        # Minimum read capacity
        maximum: 2000     # Maximum read capacity
        usage: 0.75       # Targeted usage percentage
      write:
        minimum: 5        # Minimum write capacity
        maximum: 2000     # Maximum write capacity
        usage:  0.75      # Targeted usage percentage
  #############################################################

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-tracing
  - serverless-log-forwarding
  - serverless-dynamodb-autoscaling

package:
  exclude:
    - README.md
    - buildspec.yml
    - test/**
    - .idea/**
    - .nyc_output/**